default: &default
  adapter: postgresql
  host: localhost
  username: alex
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: swtdemo_development

test:
  <<: *default
  database: swtdemo_test
